added updated sponsor logos in powered section
cesium/HeartBits2020 pull request #13
Opened 2020-09-13 22:12 UTC by ribeiropdiogo

- adição dos logos na secção powered
- foram usados os logos do ficheiro com as orientações

2020-09-13 23:27 UTC, machadovilaca commented
Please change the description to English and capitalize PR title like the others

2020-09-13 23:29 UTC, machadovilaca requested changes, later dismissed
Personally I think the 'powered by' text should be lowercase and the images seem way too big

2020-09-13 23:29 UTC, machadovilaca commented on _assets/stylesheets/home/_header.sass
> +  align-items: center
Add empty line at the end of file

2020-09-14 08:42 UTC, miguelbrandao commented
> Personally I think the 'powered by' text should be lowercase

I'm not sure if it looks better
![image](https://user-images.githubusercontent.com/26719984/93063649-7a7bf180-f66e-11ea-8ac9-3b28200559f1.png)

I'm conflicted :sweat_smile:

2020-09-14 09:15 UTC, machadovilaca commented
The 2 parts of the comment are correlated, only the text at lowercase looks bad because the images are still to big

2020-09-14 09:26 UTC, ribeiropdiogo commented
I'm confused, powered by, uppercase or lowercase? The images are already smaller.

2020-09-14 09:55 UTC, miguelbrandao commented
I think the Pfizer logo is a nice size, but the other one looks small in comparison. Can you try to scale it to match the Pfizer one?

And let's give a shot to the lowercase "powered by"

2020-09-14 09:59 UTC, ribeiropdiogo commented
Ok then. The spacing is already there. I've put 5px left and right, but I will add more.

2020-09-14 14:32 UTC, miguelbrandao approved these changes

2020-09-14 14:34 UTC, merged

2020-09-14 14:35 UTC, machadovilaca commented
Looking better, right? :D