Add Contacts Page
cesium/HeartBits2020 pull request #21
Opened 2020-09-19 18:15 UTC by ribeiropdiogo

Created the contacts page for the contacts provided in the guidlines file. As the guidelines were a bit confusing, I implemented some small corrections in order to make everything more visually pleasant.

2020-09-20 15:09 UTC, machadovilaca commented
I don't really like the design, check [jmv/update_contacts_design](https://github.com/cesium/HeartBits2020/tree/jmv/update_contacts_design) and give me your opinion.

![contacts](https://user-images.githubusercontent.com/21959383/93714583-9d6d4080-fb5b-11ea-8136-2cadb8a7b3b2.png)

@ribeiropdiogo @miguelbrandao

2020-09-20 15:48 UTC, ribeiropdiogo commented
@machadovilaca i think it's very nice! Do you think the color of the icons should be the same as in the other pages or do you want to keep those colors?

2020-09-20 16:35 UTC, machadovilaca commented
I tried the other color in all icons and I did not like it, it was too monotonous.
If you like it, then you can maybe rebase that branch into this one, I created it from this.

2020-09-20 16:37 UTC, ribeiropdiogo commented
ok perfect then!

2020-09-21 09:23 UTC, machadovilaca commented
In the mobile view, instead of fitting the text content to the width, can you adjust it to be one contact per line like:

```
Redes Sociais

F_logo HackathonHeartbits
I_logo @hackathon_heartbits

Organização

M_logo cesium...
M_logo com...
M_logo img_
```

2020-09-21 16:06 UTC, miguelbrandao commented
I like the design! Just follow @machadovilaca 's suggestion and it's ready to be merged imo

2020-09-21 22:47 UTC, ribeiropdiogo commented
@machadovilaca @miguelbrandao I tweaked the options to the ratio that seemed to look the best to me. Give me your thoughts

2020-09-22 09:31 UTC, machadovilaca commented
To me, it feels like the contact text it's still being unnecessarily splitted. 
 Can you try to put the logo and the text in different divs? Something like 

```
<div class="contact icons-space">
  <a target="_blank" rel="noopener noreferrer" href="mailto:cesium@di.uminho.pt">
    <i class="fas fa-envelope cesium fa-5x" aria-hidden="true"></i>
  </a>
</div>

<div class="contact icons-space">
  <a target="_blank" rel="noopener noreferrer" href="mailto:cesium@di.uminho.pt">
    <h6>cesium@di.uminho.pt</h6>
  </a>
</div>
```

In the logo you could keep ` max-width: 25%; min-width: 20%` but increase those values for the text

2020-09-22 12:58 UTC, ribeiropdiogo commented
Theres is no need to add divs. I was forcing the text to break. I removed that option and gave the contact more width in the mobile version.

2020-09-22 17:00 UTC, machadovilaca commented
Perfect, I like it :heart:

2020-09-22 17:02 UTC, machadovilaca requested changes

2020-09-22 17:02 UTC, machadovilaca commented on _includes/contacts/contacts.html
> +</section>
Empty line at the end of file here

2020-09-22 17:02 UTC, machadovilaca commented on _includes/contacts/contactheader.html
> +</section>
Empty line at the end of file here

2020-09-22 22:37 UTC, machadovilaca approved these changes

2020-09-22 23:21 UTC, merged